version: "3"

services:
  pdns-db:
    image: mysql/mysql-server:5.7
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 128M
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=somer00tpassw0rd
      - MYSQL_DATABASE=powerdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=somepassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  pdns-server:
    build:
      dockerfile: Dockerfile
      context: pdns/
    image: theresnotime/pdns
    ports:
      - "5357:53/udp"
    networks:
      - default
    environment:
      - DEBUG=true
      - BACKEND=gmysql
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_password=somepassword
      - PDNS_gmysql_host=pdns-db
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=someapikey
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=somepassword
      - PDNS_webserver-allow-from=0.0.0.0/0,::/0
      - PDNS_version_string=anonymous
      #- PDNS_default_ttl=3600
      #- PDNS_soa_minimum_ttl=36000
      #- PDNS_default_soa_name=ns1.example.com
      #- PDNS_default_soa_mail=hostmaster.example.com
    depends_on:
      - pdns-db

  recursor:
    build:
      dockerfile: Dockerfile
      context: pdns-recursor/
    image: theresnotime/pdns-recursor
    hostname: recursor
    ports:
      - "57:53/udp"
    networks:
      - default
    environment:
      - BACKEND=mysql
      #- PDNS_master=yes
      #- PDNS_api=yes
      - PDNS_api_key=someapikey
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=somepassword
      - PDNS_version_string=anonymous
      #- PDNS_default_ttl=3600
      - PDNS_soa_minimum_ttl=36000
      #- PDNS_default_soa_name=ns1.example.com
      #- PDNS_default_soa_mail=hostmaster.example.com
    depends_on:
      - pdns-server

networks:
  default:

volumes:
  staticfiles:
    driver: local
  uploads:
    driver: local
  powerdns-mysql-data:
    driver: local
